//
//  JoinFamilyView.swift
//  ScreenTimeRewards
//
//  View for a second parent (co-parent) to join an existing family.
//  Scans the co-parent QR code generated by the subscribing parent.
//

import SwiftUI

struct JoinFamilyView: View {
    @Environment(\.colorScheme) private var colorScheme
    @Environment(\.dismiss) private var dismiss

    @State private var showScanner = false
    @State private var isJoining = false
    @State private var errorMessage: String?
    @State private var showSuccessAlert = false
    @State private var joinedFamilyName: String?

    let onJoined: () -> Void

    var body: some View {
        ZStack(alignment: .top) {
            AppTheme.background(for: colorScheme)
                .ignoresSafeArea()

            VStack(spacing: 0) {
                // Header
                headerView

                ScrollView {
                    VStack(spacing: 24) {
                        // Illustration
                        illustrationSection

                        // Instructions
                        instructionsSection

                        // Scan button
                        scanButton

                        // Help text
                        helpText
                    }
                    .padding(24)
                }
            }

            // Loading overlay
            if isJoining {
                loadingOverlay
            }
        }
        .sheet(isPresented: $showScanner) {
            QRCodeScannerView { result in
                showScanner = false
                handleScanResult(result)
            }
        }
        .alert("Welcome to the Family!", isPresented: $showSuccessAlert) {
            Button("Continue") {
                onJoined()
            }
        } message: {
            if let familyName = joinedFamilyName {
                Text("You've joined \(familyName). You can now monitor all connected children.")
            } else {
                Text("You've successfully joined the family. You can now monitor all connected children.")
            }
        }
        .alert("Join Failed", isPresented: Binding(
            get: { errorMessage != nil },
            set: { if !$0 { errorMessage = nil } }
        )) {
            Button("Try Again") {
                errorMessage = nil
                showScanner = true
            }
            Button("Cancel", role: .cancel) {
                errorMessage = nil
            }
        } message: {
            Text(errorMessage ?? "An error occurred while joining the family.")
        }
    }

    // MARK: - Header

    private var headerView: some View {
        ZStack {
            HStack {
                Button(action: { dismiss() }) {
                    Image(systemName: "xmark.circle.fill")
                        .font(.system(size: 28))
                        .foregroundColor(AppTheme.brandedText(for: colorScheme).opacity(0.3))
                }
                Spacer()
            }

            Text("JOIN FAMILY")
                .font(.system(size: 16, weight: .bold))
                .tracking(2)
                .foregroundColor(AppTheme.brandedText(for: colorScheme))
        }
        .padding(.horizontal, 20)
        .padding(.vertical, 16)
    }

    // MARK: - Illustration

    private var illustrationSection: some View {
        VStack(spacing: 16) {
            ZStack {
                Circle()
                    .fill(AppTheme.vibrantTeal.opacity(0.1))
                    .frame(width: 120, height: 120)

                Image(systemName: "person.2.fill")
                    .font(.system(size: 48))
                    .foregroundColor(AppTheme.vibrantTeal)
            }

            Text("Join as Co-Parent")
                .font(.system(size: 24, weight: .bold))
                .foregroundColor(AppTheme.brandedText(for: colorScheme))

            Text("Your partner has already set up ScreenTimeRewards. Join their family to monitor together.")
                .font(.system(size: 15))
                .foregroundColor(AppTheme.brandedText(for: colorScheme).opacity(0.7))
                .multilineTextAlignment(.center)
        }
    }

    // MARK: - Instructions

    private var instructionsSection: some View {
        VStack(alignment: .leading, spacing: 16) {
            InstructionRow(
                number: 1,
                text: "Ask your partner to open their ScreenTimeRewards app"
            )

            InstructionRow(
                number: 2,
                text: "They should go to Settings > Invite Co-Parent"
            )

            InstructionRow(
                number: 3,
                text: "Scan the QR code displayed on their screen"
            )
        }
        .padding(20)
        .background(
            RoundedRectangle(cornerRadius: 16)
                .fill(AppTheme.card(for: colorScheme))
        )
    }

    // MARK: - Scan Button

    private var scanButton: some View {
        Button(action: { showScanner = true }) {
            HStack(spacing: 12) {
                Image(systemName: "qrcode.viewfinder")
                    .font(.system(size: 20))

                Text("Scan Partner's Code")
                    .font(.system(size: 17, weight: .bold))
            }
            .foregroundColor(.white)
            .frame(maxWidth: .infinity)
            .frame(height: 56)
            .background(AppTheme.vibrantTeal)
            .cornerRadius(16)
        }
    }

    // MARK: - Help Text

    private var helpText: some View {
        VStack(spacing: 8) {
            Text("No subscription needed")
                .font(.system(size: 13, weight: .semibold))
                .foregroundColor(AppTheme.vibrantTeal)

            Text("As a co-parent, you share the family subscription. Only one parent needs to pay.")
                .font(.system(size: 13))
                .foregroundColor(AppTheme.brandedText(for: colorScheme).opacity(0.6))
                .multilineTextAlignment(.center)
        }
    }

    // MARK: - Loading Overlay

    private var loadingOverlay: some View {
        ZStack {
            Color.black.opacity(0.4)
                .ignoresSafeArea()

            VStack(spacing: 16) {
                ProgressView()
                    .scaleEffect(1.5)
                    .tint(.white)

                Text("Joining Family...")
                    .font(.system(size: 16, weight: .medium))
                    .foregroundColor(.white)
            }
            .padding(32)
            .background(AppTheme.vibrantTeal)
            .cornerRadius(20)
        }
    }

    // MARK: - Scan Handler

    private func handleScanResult(_ result: Result<String, Error>) {
        switch result {
        case .success(let jsonString):
            validateAndJoin(jsonString: jsonString)
        case .failure(let error):
            errorMessage = "Failed to scan QR code: \(error.localizedDescription)"
        }
    }

    private func validateAndJoin(jsonString: String) {
        // Parse the QR code
        guard let qrType = FirebaseValidationService.shared.parseQRCode(jsonString) else {
            errorMessage = "Invalid QR code. Please scan a co-parent invitation code."
            return
        }

        // Ensure it's a co-parent QR
        guard case .coParent(let payload) = qrType else {
            errorMessage = "This is not a co-parent invitation code. Please ask your partner to generate a co-parent QR code."
            return
        }

        // Check expiration
        if payload.isExpired {
            errorMessage = "This invitation has expired. Please ask your partner to generate a new code."
            return
        }

        isJoining = true

        Task {
            do {
                let result = try await FirebaseValidationService.shared.validateCoParentToken(payload: payload)

                await MainActor.run {
                    isJoining = false

                    if result.success {
                        joinedFamilyName = payload.familyName
                        showSuccessAlert = true
                    } else if let error = result.error {
                        errorMessage = error.localizedDescription
                    } else {
                        errorMessage = "Failed to join family. Please try again."
                    }
                }
            } catch {
                await MainActor.run {
                    isJoining = false
                    errorMessage = error.localizedDescription
                }
            }
        }
    }
}

// MARK: - Instruction Row

private struct InstructionRow: View {
    let number: Int
    let text: String

    @Environment(\.colorScheme) private var colorScheme

    var body: some View {
        HStack(alignment: .top, spacing: 12) {
            ZStack {
                Circle()
                    .fill(AppTheme.vibrantTeal)
                    .frame(width: 28, height: 28)

                Text("\(number)")
                    .font(.system(size: 14, weight: .bold))
                    .foregroundColor(.white)
            }

            Text(text)
                .font(.system(size: 15))
                .foregroundColor(AppTheme.brandedText(for: colorScheme))
                .fixedSize(horizontal: false, vertical: true)

            Spacer()
        }
    }
}

// MARK: - Preview

#Preview {
    JoinFamilyView(onJoined: {})
}
